services:
  dgrid-data-crawler:
    build:
      context: .
      dockerfile: Dockerfile
    image: dgrid-data:latest
    container_name: dgrid-data-crawler
    restart: unless-stopped
    env_file:
      - .env
    command: npm run pm2:runtime
    networks:
      - dgrid-network

  dgrid-data-api:
    image: dgrid-data:latest
    container_name: dgrid-data-api
    restart: unless-stopped
    env_file:
      - .env
    command: npm run pm2:api:runtime
    ports:
      - "3000:3000"
    depends_on:
      - dgrid-data-crawler
    networks:
      - dgrid-network

networks:
  dgrid-network:
    external: true
